FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
LABEL author="Tom Hebert <tom.hebert@obj-ex.com>"
ENV APPLOC /app
WORKDIR /app
EXPOSE 5000
COPY published/ ./
ENTRYPOINT ["dotnet", "VgaUI.Server.dll"]
